spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password:
    url: jdbc:h2:mem:registrodb;DB_CLOSE_DELAY=-1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      data-locations: classpath:personas.sql
      mode: always
  h2:
    console:
      enabled: true